drivers: qca-wifi-host-cmn: Fix error cause a function declaration is deprecated
clang 15.0 warns:

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/target_if/core/src/target_if_main.c:91:40: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void
1 error generated.

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.c:1288:34: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void
1 error generated.                                                                              make[4]: *** [../scripts/Makefile.build:338: drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.o] Error 1

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/umac/scan/dispatcher/src/wlan_extscan_api.c:103:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
wlan_extscan_global_deinit()
                          ^
                           void
1 error generated.

Change-Id: I8722f15a707a9e5e6bc0a88479b41b0cc318a124
Signed-off-by: fadlyas07 <mhmmdfdlyas@gmail.com>
[frostg-012: Fix another error cause a function declaration is deprecated]
Signed-off-by: Vayruz Rafli <frost@nusantararom.org>